<?php

namespace InventoryBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getParentOnly()
	{
		return $this
		->createQueryBuilder('c')
		->where('c.parent IS NULL')
		;
	}
	
	public function getLikeQueryBuilder($pattern)
	{
		return $this
		->createQueryBuilder('c')
		->where('c.name LIKE :pattern')
		->setParameter('pattern', $pattern)
		;
	}
}
