<?php

namespace InventoryBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
	public function getParentOnly($id=0)
	{
		if ($id > 0) {
			return $this
			->createQueryBuilder('c')
			->where('c.parent IS NULL AND c.id !='.$id)
			->orderBy('c.name', 'ASC')
			;
		} else {
			return $this
			->createQueryBuilder('c')
			->where('c.parent IS NULL')
			->orderBy('c.name', 'ASC')
			;
		}
	}
	
	public function getLikeQueryBuilder($pattern)
	{
		return $this
		->createQueryBuilder('c')
		->where('c.name LIKE :pattern')
		->setParameter('pattern', $pattern)
		;
	}
}
