<?php

namespace InventoryBundle\Repository;

/**
 * DeliveryProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryProductRepository extends \Doctrine\ORM\EntityRepository
{
}
