<?php

namespace InventoryBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function getActiveProductByEANCode($eanCode, $direction='IN')
	{
		$q = $this->createQueryBuilder('q');
		$q
		->where('q.isActive = true');
		
		if($direction=='IN') {
			$q
			->andwhere('q.inBarcode = :p')
			->setParameter(':p', $eanCode);
		} else {
			$q
			->andwhere('q.outBarcode = :p')
			->setParameter(':p', $eanCode);
		}
	
		return $q
		->getQuery()
		->getOneOrNullResult()
		;
	}
	
	public function findAllPrintableByParentCategory($parentCategory)
	{
		$subQueryBuider = $this->createQueryBuilder('sq');
		
		$subQuery = $subQueryBuider
			->select(['c.id'])
			->from('InventoryBundle:Category', 'c')
			->where('c.parent = :param')
			->orwhere('c.id = :param')
			->setParameter('param', $parentCategory)
			->getQuery()
			->getArrayResult()
		;
			
		$qb = $this->createQueryBuilder('q');
		
		$query = $qb
			->select(['p'])
			->from('InventoryBundle:Product', 'p')
			->where($qb->expr()->in('p.category', ':subQuery'))
			->setParameter('subQuery', $subQuery)
			->getQuery()
			;

		return $query->getResult();
	
	}
}
