<?php

namespace InventoryBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
	public function getActiveProductByEANCode($eanCode, $direction='IN')
	{
		$q = $this->createQueryBuilder('q');
		$q
		->where('q.isActive = true');
		
		if($direction=='IN') {
			$q
			->andwhere('q.inBarcode = :p')
			->setParameter(':p', $eanCode);
		} else {
			$q
			->andwhere('q.outBarcode = :p')
			->setParameter(':p', $eanCode);
		}
	
		return $q
		->getQuery()
		->getOneOrNullResult()
		;
	}
}
