<?php

namespace InventoryBundle\Repository;

/**
 * SiteStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
