<?php

namespace InventoryBundle\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getSiteWithStatus($siteId, array $status)
	{
		$qsite = $this->createQueryBuilder('site');
		$qsite
			->join('site.status', 'status')
			->addSelect('status')
		;
		
		$qsite
			->where('site.id = :id')
			->setParameter(':id', $siteId);
		
		$qsite->andWhere($qsite->expr()->in('status.status', $status));
		
		return $qsite
			->getQuery()
			->getOneOrNullResult()
		;
	}
}
