inventory_product:
    resource: "@InventoryBundle/Resources/config/routing/product.yml"
    prefix:   /product

inventory_site:
    resource: "@InventoryBundle/Resources/config/routing/site.yml"
    prefix:   /site

inventory_delivery:
    resource: "@InventoryBundle/Resources/config/routing/delivery.yml"
    prefix:   /delivery
    
inventory_category:
    resource: "@InventoryBundle/Resources/config/routing/category.yml"
    prefix:   /category

generate_barcode:
    path:     /genCode
    defaults: { _controller: InventoryBundle:Listing:generateImgBarcode }
    
print_products_book:
    path:     /printProductsBook
    defaults: { _controller: InventoryBundle:Listing:printProductsBook }
    
print_sites_book:
    path:     /printSitesBook
    defaults: { _controller: InventoryBundle:Listing:printSitesBook }

print_site_resume:
    path:     /printRapportChantier
    defaults: { _controller: InventoryBundle:Listing:printSiteResume }

test_barcode:
    path:     /barcode/{code}
    defaults: { _controller: InventoryBundle:App:barcodeImage }