# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        abstract: true
    
    import.csvtoarray:
        class: InventoryBundle\Services\ConvertCsvToArray

    app.test_subscriber:
        class: InventoryBundle\Form\EventListener\TestSubscriber
        tags:
            - { name: kernel.event_subscriber }
    app.barcode:
        class: InventoryBundle\Utils\ExtendedBarcode
        
    app.form.type.deliveryproduct:
        class: InventoryBundle\Form\DeliveryProductType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    