easy_admin:
    entities:
        Delivery:
            class: InventoryBundle\Entity\Delivery
            label: 'Livraisons'
            list:
                title: 'Liste des livraisons'
                sort: ['deliveryDate', 'DESC']
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'deliveryDate', label: 'Date' }
                    - { property: 'site', label: 'Chantier' }
                    - { property: 'docType', label: 'Type' }
                    - { property: 'deliveryProducts', label: '# Produits' }
                    - { property: 'totalCost', label: 'Coût total', format: '%.2f'}
            show:
                fields:
                    - 'id'
                    - { property: 'deliveryDate', label: 'Date' }
                    - { property: 'site', label: 'Chantier' }
                    - { property: 'docType', label: 'Type' }
                    - { property: 'totalCost', label: 'Coût total'}
                    - { property: 'deliveryProducts', label: 'Liste des articles' }
            form:
                fields:
                    - { type: 'group', label: 'Détail livraison', icon: 'truck', css_class: 'col-sm-4' }
                    - { property: 'docType', label: 'Type' }
                    - { property: 'deliveryDate', label: 'Date du bulletin' } 
                    - { property: 'site', label: 'Chantier' }
                    - { type: 'group', css_class: 'new-row' }
                    - { property: 'deliveryProducts', label: 'Articles', type: 'collection', type_options: {entry_type: 'InventoryBundle\Form\DeliveryProductType', by_reference: false} }