easy_admin:
    entities:
        Product:
            class: InventoryBundle\Entity\Product
            label: 'Produits'
            list:
                title: 'Liste des articles'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - id
                    - name
                    - unit
                    - { property: 'costPrice', format: '%.2f', css_class: text-right }
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
                    - category
                    - displayOrder
                    - stock
                    - comment
                    - isActive
                    - toBePrinted
            show:
                fields:
                    - id
                    - { property: 'name', css_class: 'large' }
                    - comment
                    - isActive
                    - costPrice
                    - salePrice
                    - { property: 'inBarcode', type: 'string'}
                    - { property: 'outBarcode', type: 'string' }
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
                    - category
                    - displayOrder
            form:
                title: 'Edition article (%%product%%)'
                fields:
                    - { type: 'group', css_class: 'col-sm-8', label: 'Caractéristiques', icon: 'pencil' }
                    - { property: 'name', css_class: 'large' }
                    - { property: 'comment', label: 'Remarque' }
                    - { type: 'divider' }
                    - { property: 'unit', label: 'Unité', css_class: 'small'}
                    - { property: 'category' }
                    - { property: 'imageFile', label: 'Fichier image', type: 'vich_image' }
                    - { type: 'group', css_class: 'col-sm-4', label: 'Codes barres', icon: 'cube' }
                    - { property: 'inBarcode', type_options: {disabled: 'true'}, label: 'Code barre pour entrée en stock' }
                    - { property: 'outBarcode', type_options: {disabled: 'true'}, label: 'Code barre pour sortie de stock' }
                    - { type: 'group', css_class: 'col-sm-4', label: 'Divers', icon: 'dollar' }
                    - { property: 'costPrice', label: 'Prix de revient' }
                    - { property: 'salePrice', label: 'Prix de vente' }
                    - { property: 'stock', label: 'Stock courant', help: "Il s'agit d'une information, et pas du stock réel" }
                    - { property: 'isActive', label: 'Actif' }
                    - { property: 'displayOrder', label: "Ordre d'impression" }
                    - { property: 'toBePrinted', label: 'Doit être imprimé' }
                    - { property: 'isManualAllowed', label: 'Saisie manuelle des quantités autorisée' }
                    