easy_admin:
    entities:
        Site:
            class: InventoryBundle\Entity\Site
            label: 'Chantiers'
            list:
                title: 'Liste des chantiers'
                sort: ['name', 'ASC']
                actions:
                    - { name: 'report01', label: '', icon: 'bar-chart' }
                    - { name: 'report02', label: '', icon: 'line-chart' }
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Chantier' }
                    - { property: 'address', label: 'Adresse' }
                    - { property: 'postcode', label: 'NPA', format: '%d', css_class: text-right }
                    - { property: 'city', label: 'Localité' }
                    - { property: 'status', label: 'Etat' }
                    - { property: 'deliveries', label: 'Nb livraisons'}
                    - { property: 'toBePrinted', label: 'Aff. dans liste' }
            show:
                fields:
                    - { property: 'name', label: 'Chantier' }
                    - { property: 'address', label: 'Adresse' }
                    - { property: 'postcode', label: 'NPA', format: '%d' }
                    - { property: 'city', label: 'Localité' }
                    - { property: 'status', label: 'Etat' }
                    - { property: 'toBePrinted', label: 'Affichage dans liste dépôt' }
                    - { property: 'deliveries', label: 'Livraisons'}
                    #- { property: 'deliveries', label: 'Livraisons', type: 'collection', type_options: {entry_type: 'InventoryBundle\Form\DeliveryType', allow_delete: false, allow_add: false} }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Informations', icon: 'pencil' }
                    - { property: 'name', css_class: 'large', label: 'Nom'}
                    - { property: 'status', label: 'Etat' }
                    - { property: 'toBePrinted', label: 'Affichage dans liste dépôt' }
                    - { type: 'group', css_class: 'col-sm-6', label: 'Coordonnées', icon: 'envelope-o' }
                    - { property: 'address', label: 'Adresse' }
                    - { property: 'postcode', label: 'NPA' }
                    - { property: 'city', label: 'Localité' }
                    - { type: 'group', label: 'Historique des livraisons', icon: 'money', css_class: 'col-sm-12' }
                    #- { property: 'deliveries', label: 'Livraisons'}
                    - { property: 'deliveries', label: 'Livraisons', type: 'collection', type_options: {entry_type: 'InventoryBundle\Form\DeliveryType', allow_delete: false, allow_add: false} }
                    