easy_admin:
    entities:
        Unit:
            class: InventoryBundle\Entity\Unit
            label: 'Unités'
            list:
                title: 'Unités disponibles'
                sort: ['name', 'ASC']
                actions:
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Nom' }
                
                