product_index:
    path:     /
    defaults: { _controller: "InventoryBundle:Product:index" }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "InventoryBundle:Product:show" }
    methods:  GET

product_new:
    path:     /new
    defaults: { _controller: "InventoryBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "InventoryBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "InventoryBundle:Product:delete" }
    methods:  DELETE

product_barcode:
    path: /{id}/bar
    defaults: { _controller: "InventoryBundle:Product:barcodeHtml" }
    methods: GET
    